version: "2"
services:
  spring:
    depends_on: [mysql]
    image: ahmedbelkahia/kaddem
    container_name: spring

    restart: unless-stopped
    ports:
      - "8089:8089"


    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddemdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
    networks:
      - my_network
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: kaddemdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3037:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge